name: Build & test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew spotlessCheck assemble test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/build/test-results/*
            **/build/reports/*

  deploy:
    if: github.event_name == 'push' # only deploy for pushed commits (not PRs)
    runs-on: ubuntu-latest
    needs: [ build ]
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - name: Deploy to Sonatype
        if: ${{ github.repository == 'twitter/compose-rules' }}
        run: ./gradlew clean publish --no-parallel --no-daemon --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Add artifact version to ENV
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Publish release
        run: ./gradlew closeAndReleaseRepository
        if: success() && !endsWith(env.VERSION, '-SNAPSHOT')
        env:
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

  release:
      if: github.event_name == 'push' # only deploy for pushed commits (not PRs)
      runs-on: ubuntu-latest
      needs: [ build, deploy ]
      timeout-minutes: 30
      env:
          TERM: dumb

      steps:
          - uses: actions/checkout@v3

          - name: Copy CI gradle.properties
            run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

          - name: Setup JDK
            uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: 11

          - uses: gradle/gradle-build-action@v2
          - name: Update release draft
            uses: release-drafter/release-drafter@v5
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Add artifact version to ENV
            run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

          - name: Build the fat jars for CLI usage
            if: success()
            run: ./gradlew :rules:ktlint:shadowJar :rules:detekt:shadowJar

          - name: Upload ktlint binaries to release
            if: success()
            uses: svenstaro/upload-release-action@v2
            with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: rules/ktlint/build/libs/*.jar
                asset_name: twitter-compose-rules-ktlint
                tag: latest
                prerelease: true
                overwrite: true

          - name: Upload detekt binaries to release
            if: success()
            uses: svenstaro/upload-release-action@v2
            with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: rules/detekt/build/libs/*.jar
                asset_name: twitter-compose-rules-detekt
                tag: latest
                prerelease: true
                overwrite: true
